#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

 # Activate virtualenv
. /env/bin/activate

# Run migrations and start server
python3 ./watchmate/manage.py migrate

python3 ./watchmate/manage.py runserver 0.0.0.0:8000
