#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python3 /app/manage.py collectstatic --noinput
gunicorn config.wsgi --workers=3  --worker-connections=1000 --worker-class=gevent --timeout=10 --bind 0.0.0.0:5000 --chdir=/app
