# Generated by Django 5.2.8 on 2025-11-12 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="description",
            new_name="storyline",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="watchlist",
                to="watchlist_app.streamplatform",
            ),
        ),
    ]
