# Generated by Django 5.2.8 on 2025-11-12 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0003_streamplatform_active_reviews"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={},
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="id",
        ),
        migrations.AddField(
            model_name="reviews",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
