#!/bin/sh
BACKUP_FILE_NAME_PATH=/usr/local/bin/backup.bak
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=database_name
POSTGRES_USER=AAAAA
POSTGRES_PASSWORD=BBBB

pg_restore -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -Fc -d $POSTGRES_DB $BACKUP_FILE_NAME_PATH --no-acl -v 